{{- if .Values.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: api-service-lb
  namespace: {{ include "microservices.namespace" . }}
  labels:
    app: api-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: api-service
{{- end }}
