# configmap is used to de-couple configuration from code
# it is used to change postgres's user or port directly without rebuilding docker image
# no of configmaps -> 1) api-config 2) postgres-config

apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: microservices
  labels:
    app: api-service
data:
  NODE_ENV: "production"
  PORT: "3000"
  PGHOST: "postgres-service"
  PGPORT: "5432"
  PGDATABASE: "appdb"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: microservices
  labels:
    app: postgres
data:
  POSTGRES_DB: "appdb"
  PGDATA: "/var/lib/postgresql/data/pgdata"
